name: Diagram

on:
  pull_request:
      branches:
        - main
env:
  CI: true

jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Update diagram
      uses: githubocto/repo-visualizer@main
      with:
        output_file: 'structure.svg'
        excluded_paths: '.github,.flayignore,.inch.yml,.rubocop.yml,.ruby-version,CHANGELOG.md,CODE_OF_CONDUCT.md,Gemfile,Gemfile.lock,LICENSE.txt,Rakefil,reviewer.gemspec,README.md,bin,exe,test,vendor,structue.svg'
